#!/usr/bin/env python3
#
# Parser loads lava.py module and convert template in Jinja2 format into Job configuration in YAML.
#
# Options:
# $1 - Parse absolute relative path where module (lava) is loaded.
# $2 - Parse absolute relative path where Jinja2 Template is stored.
# $3 - Parse job name (e.g. nightly-x86-64)
# $4 - Parse build number else defaults to None
# $5 - Device definitions for (Minnowboard, Beaglebone, Edgerouter, x86) in lava modules.
# python3 scripts/run-jinja-parser lava/device/bsp-packages.jinja2 nightly-x86-64-bsp None minnowboard
import os
import sys
import re
import json
import jinja2
import time
import utils
from jinja2 import Template, Environment, FileSystemLoader

os.environ["ABHELPER_JSON"]="config.json /home/ab/Downloads/yocto-autobuilder-helper/config-intelqa-x86_64-lava.json"

def jinja_helper():
    print("USAGE: python3 run-jinja-parser <Module Path> <Jinja Template> <Build Name> <Build num> <Device>")
    sys.exit(0)

def jinja_writer(name, data):
    yamlFile=name + ".yaml"
    yamlNewFile= "-".join([name, time.strftime("%d%m%Y-%H%M%S")]) + ".yaml"
    if os.path.isfile(yamlFile):
        os.rename(yamlFile, yamlNewFile)
        print("INFO: Found previous job config [%s] & rename to [%s]" % (yamlFile, yamlNewFile))
    with open(yamlFile, "w+") as fh:
        fh.write(data)
    fh.close()

# Handles data expansion based on pattern matching
def getconfig_expand(config, ourconfig, pattern, match, buildname, buildnum):
    newconfig={}
    expansion=re.compile(pattern)
    for items in ourconfig.items():
        if items[0] in match:
            if items[0] in "DEPLOY_DIR":
                imagedeploy= "file://" + os.path.join(items[1], buildname)
                newconfig[items[0]] = imagedeploy
                if buildnum is not None and buildnum != "None":
                    newconfig[items[0]] = os.path.join(imagedeploy, str(buildnum))
            else:
                newconfig[items[0]] = items[1]
            config=config.replace('${' + items[0] + '}', newconfig[items[0]])
    newconfig['DEPLOY_DIR_IMAGE']=config
    return newconfig['DEPLOY_DIR_IMAGE']

try:
    jinjaTempl=sys.argv[1]
    target=sys.argv[2]
    buildnum=sys.argv[3]
    device=sys.argv[4]
except:
    jinja_helper()

ourconfig  = utils.loadconfig()
jobconfig  = ourconfig['overrides'][target]
lavaconfig = ourconfig['lava-devices'][device]
deploydir  = getconfig_expand(jobconfig['DEPLOY_DIR_IMAGE'], jobconfig, "\${(.+)}/images/\${(.+)}/", ['DEPLOY_DIR', 'MACHINE'], target, buildnum)
newconfig  = { 'DEPLOY_DIR_IMAGE' : deploydir }

for img in ['kernel', 'modules', 'nfsrootfs']:
    lavaconfig['deploy'][img]['url'] = getconfig_expand(lavaconfig['deploy'][img]['url'], newconfig, "\${(.+)}.+", ['DEPLOY_DIR_IMAGE'], target, buildnum)
lavaconfig['device_type'] = device

if not os.path.isfile(jinjaTempl):
    print("ERROR: Unable to find Jinja2 Template: [%s]" % jinjaTempl)
    sys.exit(1)
#
# JSON Dumps
#
debug=True
if debug:
    print(json.dumps(lavaconfig, indent=4))

jinjaPath = "/".join(jinjaTempl.split("/")[0:-1])
jinjaFile = jinjaTempl.split("/")[-1]

templateLoader = jinja2.FileSystemLoader(searchpath=jinjaPath)
templateEnv    = jinja2.Environment(loader=templateLoader)
templateJinja  = templateEnv.get_template(jinjaFile)
outText        = templateJinja.render(lavaconfig)

jinja_writer(target, outText)

print("INFO: Job configuration [%s] is ready to be triggered in next step" % target)
